### ISSUE TITLE
Building the docs on RTD is broken

### ISSUE THREAD

**Issue by icemac** [zopefoundation/zope.app.onlinehelp#11]
See https://readthedocs.org/projects/zopeapponlinehelp/builds/

@jamadden You are the only developer at RTD for this project. Could you please fix it over there or add me (`icemac`), so I can fix it myself?

**Comment by jamadden** [comment]
I've done both :) 

(Fixing the build was accomplished by switching the builders from Python 2 to Python 3; it was having problems installing zope.container for some reason. This is something that really ought to be managed by .readthedocs.yml files in the repo, as opposed to the RTD GUI, moving forward.)
